version: '3.8'

services:
  server1:
    image: golang
    container_name: server1
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8081:8080"
    command: ["go", "run", "main.go"]
    environment:
      - SERVER_NAME=server1
    networks:
      - go_network

  server2:
    image: golang
    container_name: server2
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8082:8080"
    command: ["go", "run", "main.go"]
    environment:
      - SERVER_NAME=server2
    networks:
      - go_network

  server3:
    image: golang
    container_name: server3
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8083:8080"
    command: ["go", "run", "main.go"]
    environment:
      - SERVER_NAME=server3
    networks:
      - go_network

networks:
  go_network:
    driver: bridge

