services:
  server1:
    image: golang
    container_name: server1
    working_dir: /app
    volumes:
      - ./:/app
    command: ["sh", "run.sh"]
    environment:
      - SERVER_NAME=server1
    networks:
      - go_network
    ports:
      - "6061:6060" # Map host port 6061 to container port 6060 for pprof

  server2:
    image: golang
    container_name: server2
    working_dir: /app
    volumes:
      - ./:/app
    command: ["sh", "run.sh"]
    environment:
      - SERVER_NAME=server2
    networks:
      - go_network
    ports:
      - "6062:6060" # Map host port 6062 to container port 6060 for pprof

  server3:
    image: golang
    container_name: server3
    working_dir: /app
    volumes:
      - ./:/app
    command: ["sh", "run.sh"]
    environment:
      - SERVER_NAME=server3
    networks:
      - go_network
    ports:
      - "6063:6060" # Map host port 6063 to container port 6060 for pprof

networks:
  go_network:
    driver: bridge

